TRAINING_DATABASE = [
  # Suicida
  ('Tenho vontade de sumir', True),
  ('Sou um peso para a minha família', True),
  ('Sou um peso para a minha esposa', True),
  ('Ninguém me aguenta mais', True),
  ('Eu não me sinto amado por ninguém', True),
  ('Sou um estorvo', True),
  ('Me sinto muito frustrado a com a vida', True),
  ('Eu não passo de um grande fracassado', True),
  ('Estou planejando me matar', True),
  ('Só queria dormir e nunca mais acordar', True),
  ('Não tenho conseguido mais dormir', True),
  ('Preciso de um remédio para dormir', True),
  ('Vou tomar uma cartela inteira de remédios', True),
  ('Me sinto muito depressivo e deprimido', True),
  ('A vida é uma merda bosta', True),
  ('Sou apenas alguém inútil', True),
  ('Me sinto frio e perdido em desespero, não tenho mais esperança, o fracasso é tudo que eu conheço', True),
  ('Me sinto muito só', True),
  ('Eu queria dormir para sempre', True),
  ('Vou ficar no meu quarto fingindo que não existo', True),
  ('Não aguento mais a minha vida', True),
  ('Não sinto mais vontade de viver', True),
  ('Não vejo mais alegria na vida', True),
  ('Sinto que sou uma decepção para as pessoas que amo', True),
  ('Ninguém entende a minha depressão se tenho tudo o que preciso', True),
  ('Não consigo ver graça na vida', True),
  ('Eu me sinto apático em relação às coisas', True),
  ('Me sinto muito solitário', True),
  ('Sou uma pessoa muito sozinha e triste', True),
  ('Quero acabar logo com tudo isso', True),
  ('Vou tomar uma cartela inteira de remédios', True),
  ('Quero atar uma corda em meu pescoço', True),
  ('Amanhã estou planejando me enforcar', True),
  ('Eu não quero mais viver desse jeito', True),
  ('Eu não gosto de mim mesmo', True),
  ('Vou dar um tiro na minha cabeça e acabar logo com isso', True),
  ('Vou tomar veneno para acabar com a minha vida', True),
  ('Tem um cachorro preto aos pés da minha cama', True),
  ('Vou saltar do quarto andar', True),
  ('Vou me jogar do prédio', True),
  ('Vou saltar na frente do metrô quando ele estiver passando', True),
  ('Vou me entupir de paracetamol para sumir', True),
  ('Vejo os dias passarem sem nada acontecer de bom em minha vida', True),
  ('Preciso organizar tudo antes de consumar o ato', True),
  ('Do que adianta ter tudo o que quero se nada me faz feliz', True),
  ('Eu acho que a única solução é eu me matar', True),
  ('Amanhã eu finalmente irei cometer suicídio', True),
  ('Minha vontade é cometer suicídio', True),
  ('Nada faz sentido', True),
  ('Vou me suicidar pois não vejo graça nas coisas', True),
  ('Estou atolado em dívidas e não vejo mais solução senão me matar', True),
  ('Depois de todos estes anos, não consegui atingir nenhum objetivo na vida', True),
  ('Sinto que não vivo, apenas existo nessa sociedade doente', True),
  ('Não aguento mais os problemas que me assombram todos os dias, preciso dar um fim a isso', True),
  ('Tenho muitas mágoas, não consigo ver nada de positivo na minha realidade', True),
  ('Vou me jogar no rio para me afogar', True),
  ('Não consigo mais suportar sozinho as coisas que acontecem comigo', True),
  ('Vou tomar um remédio para dormir e nunca mais voltar', True),
  ('Me sinto muito só estou sozinho nesse mundo', True),
  ('Tenho andado com muita insonia e paranoia', True),
  ('Nos últimos dias tenho tomando muitos compromidos para dormir', True),
  ('Já não sinto mais vontade de viver', True),
  ('Sou uma aberração nessa sociedade', True),
  ('Me sinto um frouxo diante das coisas que me rodeiam', True),
  ('Minha esposa ou meu esposo não me ama mais', True),
  ('Choro todos os dias pois a minha vida é péssima e horrível muito ruim', True),
  ('Já está tudo acabado não há mais solução para os meus problemas', True),
  ('foi muito bom te conhecer, até mais', True),
  ('Todo dia é um pouco pior cercado por todos os lados o dia é longo e difícil e só quero que tudo acabe', True),
  ('Tento procurar sentido e prazer nas coisas do cotidiano mas não consigo é muito difícil', True),
  ('Você não me ama mais então não vejo mais razões para viver', True),
  ('Um dia tive muitas coisas na vida mas hoje sinto um vazio dentro de mim', True),
  ('Durante todos estes anos tudo que eu vivi foi uma grande ilusão', True),
  ('Quero cessar a minha existência no planeta terra', True),
  ('Os antidepressivos não estão funcionando para mim e só penso em me matar', True),
  ('Cada dia que passa é mais difícil encontrar razões para existir', True),
  ('Gostaria que uma doença mortal me levasse', True),
  ('Vou tomar uma caixa inteira de comprimidos', True),
  ('Vou me atirar de cima da ponte para nunca mais voltar', True),
  ('Não tenho vontade de levantar da cama', True),
  ('Quero te matar e depois me matar', True),
  ('Quero morrer', True),
  ('Queria estar morto', True),

  # Não-suicida
  ('Preciso acabar o trabalho de tópicos especiais em computação', False),
  ('Eu não quero me matar', False),
  ('Eu adoro viver', False),
  ('Estou sentindo uma grande alegria', False),
  ('Eu me sinto feliz', False),
  ('Recebi um aumento de salário', False),
  ('Perdi meu emprego, mas já estou procurando um novo', False),
  ('Ontem eu fui demitido', False),
  ('Eu amo a minha família', False),
  ('Eu amo a minha esposa', False),
  ('Eu sou amado por todos', False),
  ('Ninguém me odeia, todos gostam de mim', False),
  ('A melhor coisa é acordar de manhã e ver este céu lindo', False),
  ('O preço dos alimentos tem subido', False),
  ('Meu marido é um inútil', False),
  ('Tenho esperança que as coisas darão certo', False),
  ('Só queria que este momento durasse para sempre', False),
  ('Eu sou admirado por muitos', False),
  ('Fui bem na prova', False),
  ('Fui mal na prova', False),
  ('Este lugar é apavorante', False),
  ('Tome cuidado lá fora', False),
  ('Tenha juízo menino', False),
  ('Estou sentindo muito medo', False),
  ('Estou com medo do resultado dos meus testes', False),
  ('Se eles descobrirem estamos encrencados', False),
  ('O amor não se vê com os olhos mas com o coração', False),
  ('Eike Batista é condenado a 30 anos de prisão na Lava Jato do Rio', False),
  ('A sociedade é composta por muitos indivíduos que pensam diferente entre si', False),
  ('Estou organizando uma grande viagem e vou me divertir muito', False),
  ('Ano que vem irei viajar para os Estados Unidos', False),
  ('Vou te ensinar a atar os tênis', False),
  ('Praticar esportes faz muito bem para a saúde', False),
  ('Eu quero viver cada dia como se fosse o último', False),
  ('Eu quero viver mais e mais', False),
  ('Que delícia tomar um refrigerante bem gelado', False),
  ('Descobri que tenho asas para voar', False),
  ('Preciso acordar cedo amanhã', False),
  ('Vou jogar no jogo do bicho', False),
  ('Os políticos são todos corruptos', False),
  ('O Lula esteve envolvido em muitos escândalos como o mensalão', False),
  ('Vou votar no Lula ou no Bolsonaro', False),
  ('Dou graças a deus por tudo o que tenho', False),
  ('Às vezes é necessário pensar fora da caixa', False),
  ('Sou grato pelas pessoas e coisas boas que tenho em minha vida', False),
  ('A economia está ruim, não consigo poupar dinheiro', False),
  ('Estou com a conta negativa no banco', False),
  ('Vou tomar uma cocacola com sorvete', False),
  ('Vou comprar um apartamento de trezentos mil reais', False),
  ('Não tenho tudo o que eu quero, mas sou feliz', False),
  ('Estou muito gordo, preciso fazer exercícios e arrumar a minha alimentação', False),
  ('A vida é boa', False),
  ('Eu quero viver', False),
  ('Bandido bom é bandido morto', False),
  ('Neymar levou um pisão no tornozelo de Layún', False),
  ('Nessa copa do mundo o brasil vai ser hexa campeão', False),
  ('Crianças morrem de fome todo dia na África', False),
  ('Meu carro está caindo aos pedaços', False),
  ('Incêndio florestal avança na Califórnia e ameaça centenas de casas', False),
  ('Hoje vou passar o dia inteiro na praia e ver o por do sol', False),
  ('Minhas comidas favoritas são hamburguer sushi milkshake e batata frita', False),
  ('Sexta feira é o dia de tomar uma cerveja bem gelada com os amigos', False),
  ('Vou na festa para dançar e tomar umas biritas cervejas', False),
  ('A vida é bela', False),
  ('Um bom livro um café e um cigarro', False),
  ('Hoje eu dormi uma boa noite de sono', False),
  ('Sorrio todos os dias', False),
  ('Estou tendo um péssimo dia', False),
  ('Nem todos os dias são fáceis mas é preciso persistência para ser feliz e eu sou', False),
  ('Se alguém já lhe deu a mão e não pediu mais nada em troca pense bem pois é um dia especial', False),
  ('Mas te vejo e sinto o brilho desse olhar que me acalma e me traz força para encarar tudo', False),
  ('Você já sabe que em qualquer lugar eu estou pensando em você', False),
  ('Te amo muito você é o amor da minha vida', False),
  ('Meu programa preferido é ir ao shopping e ver a namorada no fim de semana', False),
  ('Estou há horas colocando frases aqui e estou ficando sem criatividade me ajuda senhor', False),
  ('Queria poder viajar ver o mar', False),
  ('Sofri uma contusao jogando bola e to pensando em me retirar dos campos', False),
  ('Vou te matar', False),
  ('Vou matar você com muitos tiros', False),
  ('Fui muito mal nas provas e agora estou pensando que talvez eu deva tomar jeito e estudar com antecedencia', False),
  ('Quero pegar a estrada ouvindo música no meu carro em um dia ensolarado', False),
  ('Nada me tira o ânimo e a alegria de viver', False),
  ('Estou no fim de semestre e falta pouco para a formatura', False),
  ('No verão eu adoro acampar e entrar em contato com a natureza', False),
  ('Vou dar um banho em meu cachorro e meu gato', False),
  ('Adoro gosto de andar de carro', False),
  ('Queria estar em Paris', False),
  ('Nessa mágica eu faço uma moeda sumir', False),
  ('Nesse fim de semana coloquei o pé na jaca, me entupi de hamburguer e batata frita', False),
  ('Nossa, que bom jogar futebol novamente, eu nunca mais tinha jogado', False),
  ('A vaca foi beber água sozinha', False),
  ('Bezerros desmamados choram na ausência de suas mães', False)
]
